### ISSUE TITLE
Search Interface

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#1]
Implement layout and features for APC record search.

Design template:

![muk---search](https://cloud.githubusercontent.com/assets/856138/15314943/afa59ece-1c0c-11e6-86ea-e88e0898c558.jpg)

Fields to provide facet over:
- Publisher - We probably want the OR search here, but it's possible AND would be better, or the ability to switch between them (the latter would require some thought as to how to implement seamlessly).  For the final layout, if using OR, use the checkbox approach as per the design template.
- Others ...

**Comment by tdcodesthings** [comment]
It strikes me that we should consider adding a date range (similar concept to as is used on the other reports), so that users can search for APCs within a range. Do you agree?

**Comment by Steven-Eardley** [comment]
I agree - that shouldn't be too difficult to include. Should the range selector be in the same place as on the other reports, or on the left hand side with the other search controls?

**Comment by tdcodesthings** [comment]
Yes, left hand side with the other facets. I can provide a design in due course

**Comment by tdcodesthings** [comment]
Newer mockup of search interface available [here](https://invis.io/WN7ABGOZF#/170988726_Search_).
Headline changes:
- Sort results
- Result 'card' says that price is inclusive of VAT
- Added facets for Date and Journal type
- Improved the 'Duplicates' bit (I propose that this one is 'closed' intitially)
- Improved the styling of the checkbox + filter bit
- Added 'breadbox', so that users' query is recorded in a logical place.
- Added the share/save bit - [here's how that would work](https://invis.io/WN7ABGOZF#/170988725_Search___Share_).

**Comment by richard-jones** [comment]
Just a few comments, as I go about the implementation:
- You have the paging controls at the bottom of the page only - in our experience, this is annoying for users, especially if there are a lot of results on a page
- Same comment with regard to the "items per page" control

For these, do you want to consider putting the same controls at the top of the page too?

**Comment by richard-jones** [comment]
How do you feel about keeping the date ranging features consistent with the reports?

Part of my motivation for this (other than consistency) is that fitting the control into the space available for the facet is going to be relatively tricky!

**Comment by tdcodesthings** [comment]
I think it's important to have it in the same part of the page as the facets, ie in the sidebar. Even if the price we pay is that it's presented differently to on the report pages. I guess that might mean that it's laid out a little different in order to get it to fit (?) e.g. the 'To' and 'From' on different lines, which would be fine.

**Comment by richard-jones** [comment]
Ok, I'll look into the date ranger at some point next week.

In the mean time, the main body of the work is now complete on the search interface, if you want to review (be sure to refresh all your caches).

The only major divergence from the design is in the "results per page" and "next/previous" page functionality.  I didn't see how the design would cope with the potential number of pages (477 at the moment), so I've stuck with the original approach of "First, Prev, Next".  If you want to have another look and let me know what changes to make, I can do that.

**Comment by tdcodesthings** [comment]
There's a Jisc [pattern](https://ux.jisc.ac.uk/patterns/navigation/) for scenarios where there are many pages - is this doable?
<img width="783" alt="screen shot 2016-07-13 at 16 06 37" src="https://cloud.githubusercontent.com/assets/3832215/16808291/cc07e110-4913-11e6-9247-5603b4e45528.png">

**Comment by tdcodesthings** [comment]
There are a few CSS things we could do, but for now I'll include the couple of key things that will have the greatest impact

**1.**
Have the facets be open by default.

**2.** 
For the facet blocks which are scrollable, add a class ('.this-is-a-scrollable-div' in the example below purely for illustrative purposes). Then add the following rules to search.css.
They will ensure that webkit browsers don't hide the scrollbars as a default.

```
.this-is-a-scrollable-div::-webkit-scrollbar {
    -webkit-appearance: none;
}

.this-is-a-scrollable-div::-webkit-scrollbar:vertical {
    width: 8px;
}

.this-is-a-scrollable-div::-webkit-scrollbar:horizontal {
    height: 8px;
}

.this-is-a-scrollable-div::-webkit-scrollbar-thumb {
    border-radius: 8px;
    border: 1px solid #c4d0d7;
    background-color: rgba(0, 0, 0, .4);
}

.this-is-a-scrollable-div::-webkit-scrollbar-track { 
    background-color: #c4d0d7; 
    border-radius: 8px; 
}
```

**3.**
Add these rules to the 'headings' of the facets

```
    color: #004f77;
    font-size: 0.9em;
    font-weight: normal;
```

**4.**
Add `border-radius: 0 3px 3px 0;` to the search button.
A seemingly inconsequential change but we will get pulled up for not using jiscy buttons. :)

**Comment by richard-jones** [comment]
The search interface is now basically ready, with the following things omitted:
- we just never got enough time to do the checkbox facets
- I put the date filter in a facet, but the styles are not the same as the design, as there wasn't space.  Hopefully the compromise is ok
- I didn't do (3) from the above list, as it made the header text smaller than the body text, so I figured maybe it contained an error.

@TomYeahOK - could you take a look at the search page and then close this issue off?  If there are any other issues remaining, could you open them as new ones, as I don't want this epic issue to encompass too many bits of work, it'll be difficult to track.

**Comment by richard-jones** [comment]
We're out of time now for the first product, but I believe everything here is finished.  I'm going to bump it from the milestone but leave it open.
