### ISSUE TITLE
Trends across time

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#14]
For all suitable reports, it would be good to try to show trends across time, such as in the attached example.  Some prototyping required to understand the requirement.

![screenshot from 2016-05-17 10 33 51](https://cloud.githubusercontent.com/assets/856138/15317843/1a38cad2-1c1b-11e6-97a0-eef087f3712c.png)

Some other examples of possibilities:

![screenshot from 2016-05-17 10 59 42](https://cloud.githubusercontent.com/assets/856138/15318567/93189ac4-1c1e-11e6-88a5-2f99a3ae96e0.png)

![screenshot from 2016-05-17 10 59 55](https://cloud.githubusercontent.com/assets/856138/15318573/9726be52-1c1e-11e6-8a21-aee5e9ebfebf.png)

![screenshot from 2016-05-17 11 01 18](https://cloud.githubusercontent.com/assets/856138/15318600/b4e16c8a-1c1e-11e6-946f-f65dee21d135.png)

![screenshot from 2016-05-17 11 01 39](https://cloud.githubusercontent.com/assets/856138/15318613/c18f343a-1c1e-11e6-92e6-7185472aa54d.png)

**Comment by tdcodesthings** [comment]
The 'trends over time' thing has been agreed as a low priority therefore put on ice for now.
