### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by tdcodesthings** [JiscMonitor/monitor-uk#18]
The reports feature a date-range selector.

A good example of this is in Google Analytics which you're probably familiar with. (minus the 'compare with' aspect)

<img width="678" alt="screen shot 2016-05-23 at 10 52 18" src="https://cloud.githubusercontent.com/assets/3832215/15467094/9277ebf0-20d4-11e6-9fdf-9e8f4701d32e.png">

NB, Monitor Local are using a datepicker plugin, so it may be worth getting their comments on how good that one is.

As show in screenshots there will be a feature to define what the range applies to (APC request date, publication date).

In the first instance, the range-selector should at least let users click the dates on the panels, and enter them into text boxes.

An enhancement may be to include some options for "this academic year", "last academic yr" "this financial year", etc - Do you think these are feasible? Is there even the data to do previous years yet?

**Comment by tdcodesthings** [comment]
Here's something a little more concrete in terms of making the design work.
I've not done too much on the actual calendars as we'll see what the plugin looks like then adjust accordingly.

However it shows the rest of it. In the 'presets' list would be:
- This academic year
- Previous academic year
- This calendar year
- Previous calendar year
- This financial year
- Previous financial year

**Comment by Steven-Eardley** [comment]
A handy (and well named) resource is here: http://www.daterangepicker.com

**Comment by richard-jones** [comment]
@TomYeahOK - do you have the dates for academic and financial years?

**Comment by richard-jones** [comment]
(Is financial year the tax year?)

**Comment by tdcodesthings** [comment]
It seems there's 2 kinds of financial year. Fiscal year and tax year. The former is for corporations (1 April to 31 March); the latter is for personal tax (6 April to 5 April. So it seems we should go for the former and put in brackets (Apr 1 - Mar 31 'YR).

Academic years seem like a can of worms. Different between institutions. I guess the ultimate solution would be that institutions could set them for themselves. However given that overhead perhaps we test the temperature for this preset before we implement it?

**Comment by richard-jones** [comment]
I've put in "fiscal" year and taken "academic" year to run September - September; it's easy to take them out, so we can try them on people and see what they think

**Comment by richard-jones** [comment]
Datepicker has now been implemented, so I'm going to close off this issue.  We can open as new issues any changes required to fixed date ranges, etc.
