### ISSUE TITLE
Pre-populate oa_type with data from article type

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#26]
If an article type is known oa, use that, if known hybrid use that, otherwise use "unknown"

**Comment by ostephens** [comment]
Not sure I'm being helpful here, but isn't this confusing article type with journal type?

**Comment by richard-jones** [comment]
yes, sorry, semantics - there's a field with the kind of journal article it is (book, journal hybrid, journal oa) and we'll use that when no other information is available.

**Comment by richard-jones** [comment]
@Steven-Eardley - this is now done, so when you've re-imported the live data you can close this off

**Comment by Steven-Eardley** [comment]
Re-imported.
