### ISSUE TITLE
Reports: General styling comments

### ISSUE THREAD

**Issue by tdcodesthings** [JiscMonitor/monitor-uk#27]
The below points are apply to all **reports**. Numbered so that we can reference them.

@richard-jones I have put these all in one ticket but let me know if you want me to separate them out - can do easliy, whatever's best for you.
## 1- Outside the charts
- [ ] 1/ Title and intro text should align with left of page
- [x] 2/ Title and intro text to be Stag Sans Light font
- [ ] 3/ Title needs 'Report' label above it
- [x] 4/ Intro text content is still to come from us (currently being drafted)
- [x] 5/ Intro text to be @18px
## 2 - Improving clarity of what's being shown
- [ ] 1/ Can we have some text that shows when the report launches which explains what is being shown and why. It could disappear once a change has been made.
- [x] 2/ When there is nothing to show, can some text display in the chart area to say "There is no data to show for the options you have set."
## 3 -Tables
- [ ] 1/ Tables are getting long. We could truncate at a certain height, with a button to reveal more. Thoughts?
- [ ] 2/ 'Download CSV' link to be underlined, and beneath the table
- [ ] 3/ Tables - Some CSS that might help [make the tables easier on the eye](https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f/edit)
- [ ] 4/ Tables - Add a title to the first column
- [ ] 5/ Tables - Use <th>s for column heads
## 4 - Datepicker

Reference of designs. [Unopened](https://invis.io/WN7ABGOZF#/158597190_Publisher_Report_-_Minimal_Filter-01_). [Opened](https://invis.io/WN7ABGOZF#/172212381_Screen_Shot_2016-06-27_At_14-06-49_).
- [ ] 1/ Place it next to intro text
- [ ] 2/ When opened, calendars shouldn't disappear if a preset has been chosen
- [ ] 3/ Use a <select> for the presets, with label.
- [ ] 4/ 'opened' design may be hard to get to; but see what you can do, i.e.. layout; colour
- [ ] 5/ Continue to use a standard <select> for the 'time period' for the 'unopened' version, rather than implementing a new style as shown in my design.
- [ ]  6/ Buttons in the opened version (see below for tips)
## 5 - Filter
- [ ] 1/ S[ome CSS to help get the title of it closer to the design in this Gist](https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f/edit).
- [ ] 2/ Remove the 2px line under the word Filter
- [ ] 3/ Facet headings to be in Stag Sans Light
## 6 - Tabs on reports
- [ ] 1/ Don't use <strong>s on these as it adds a faux-bold
- [ ] 2/ Hover CSS - [see item 3 in this gist](https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f/edit)
- [ ] 3/ Add 'show:' label, per [mockup](https://invis.io/WN7ABGOZF#/158597190_Publisher_Report_-_Minimal_Filter-01_).
## 7 - Chart interaction
- [x] 1/ Currently bars are a bit transparent until you hover. They should always be opaque. The hover should add an outline. There is already css targeting these (line 82 of nv.d3.css), copy it or amend it to inlcude: stroke-opacity: 1; stroke: black;
## \- Bonus: Buttons
- [ ] [Here's some CSS that may help in styling buttons. We are moving away from the gradient ones and towards these rounded ones. Note the shadow and border-radius.](http://ux.digitalresources.jisc.ac.uk/dropbox/buttons/buttons.html).

**Comment by tdcodesthings** [comment]
Here's the [text for top of each report](https://www.dropbox.com/s/9jo38ll63izjdkg/Text%20for%20Monitor%20reports%20-%20top.docx?dl=0).

**Comment by richard-jones** [comment]
I've moved each section out to individual issues, as some are possible and some are out of scope for the first production release.  Closing this one off.
