### ISSUE TITLE
'Your Account' page

### ISSUE THREAD

**Issue by tdcodesthings** [JiscMonitor/monitor-uk#29]
- [x] 1/ Use (rounded blue button)[http://ux.digitalresources.jisc.ac.uk/dropbox/buttons/buttons.html] without icon.
- [x] 2/ 'Regenerate' button text -> 'Generate a new API key'
- [x] 3/ Style the <form>s in accordance with the examples shown [near the bottom of this page](https://ux.jisc.ac.uk/patterns/forms/). Light font for heading; blue border; etc.
- [x] 4/ QUESTION: Does 'delete account' feature have an 'are you sure' before it commits?

**Comment by richard-jones** [comment]
@TomYeahOK - The "delete account" feature doesn't have an "are you sure", but it does make you type in your password, which is a fairly deliberate act.  I can add an "are you sure" popup if necessary though.  Let me know.

**Comment by tdcodesthings** [comment]
If it's trivial, could you pop it in just for good practice; but if it's anything beyond trivial I know time is precious so we can backlog it for now

**Comment by Steven-Eardley** [comment]
Good news: it's always had an 'are you sure' dialogue on delete - @richard-jones added it [in April 2015](https://github.com/richard-jones/magnificent-octopus/blame/develop/octopus/modules/account/static/js/account/userpage.js), showing excellent foresight.

**Comment by richard-jones** [comment]
ah, magic, I'd totally forgotten - I even thought I'd double checked.
