### ISSUE TITLE
Publisher Report: Institution Pickers

### ISSUE THREAD

**Issue by tdcodesthings** [JiscMonitor/monitor-uk#31]
Some slight tweaks to presentation of the coloured dropdowns:
- [x] 1/ Match the layout shown in [mockups](https://invis.io/WN7ABGOZF#/158597189_Publisher_Report_-_Alt_Filter-01_): Label in Stag Sans Light, above the picker.
- [x] 2/ Add a box-shadow 0 0 3px #bfbfbf; to improve contrast against the white background
- [x] 3/ The colour shouldn't change when you open it up as it's useful information for the user.
- [x] 4/ If possible, use Stag Sans Web Light for the item that displays
## Amends to colours:
- Yellow: rgb(253,216,53)
- Green: rgb(76, 175, 80)

But when they don't yet have a value, fade them to these colours:
- Yellow: rgba(253,216,53,0.5)
- Green: rgba(76, 175, 80, 0.5)

**Comment by richard-jones** [comment]
I've made all the colour changes, and updated the graph to match.

I haven't done the opacity 0.5 thing, because there's no CSS rule that will allow me to set the colour of the select box based on the selected option unfortunately.
