### ISSUE TITLE
"Journal Type" facet on Expenditure per Publisher

### ISSUE THREAD

**Issue by ostephens** [JiscMonitor/monitor-uk#39]
When Tom did a quick demo of Monitor UK yesterday I noticed that on the Publisher tab the “Journal Type” facet contains different data to the same facet on the other reports. Instead of the journal type it has the publication type+journal type.

Think this either needs relabelling, or bringing in line with the Journal Type facet on other reports

**Comment by richard-jones** [comment]
Yes, this is just demo data sourced from the TCO sheets for convenience.  It will be replaced with real data once we have the Lantern integration.
