### ISSUE TITLE
Funder Report

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#4]
Rationale: Assess spend on Pure vs Hybrid OA

Primary Reporting Requirements
- APC count
- Overall expenditure
- Average expenditure

Secondary Reporting Requirements
- Min/max

Auxiliary Features
- Trends over time
- Filter by discipline?
- Comparison across institutions/across publishers?

a report wouldn’t be a single super-flexible report, but a series of quite-flexible views of the data.

Mockups:
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158596982

Each report currently has a min/max/mean. Only the mean is really key, the other two can go

We will require a default period for the report: calendar/financial/academic year/month

Investigate possibilities for trends across time (see #14 )

**Comment by richard-jones** [comment]
- [x] Note that we'll need to filter the funder terms aggregation, to ensure that only terms which also appear in the list of funder filters on the query are carried forward through the data function to the dataSeries for the graph.

**Comment by Steven-Eardley** [comment]
- [x] Next we need to embiggen the query so that results don't drop off when a large range of values is selected
- [x] And the story paragraph should respect the date filters applied to the chart

**Comment by Steven-Eardley** [comment]
@richard-jones The story section now updates according to which date range, journal type and institution are selected on the chart. It ignores selected funders, because the average is across funders. 

Is this ready to be closed off?

**Comment by richard-jones** [comment]
I did a minor fix for the case where there were filters, but none of them were funder filters - it was showing the full list of 50ish funders in those cases.  A one line fix.

Otherwise, all looks good, closing off.
