### ISSUE TITLE
Institution Report

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#5]
Rationale: Benchmark spend against other institutions

Primary Reporting Requirements
- APC count
- Overall expenditure
- Average expenditure

Secondary Reporing Requirements
- Min/max (we later consider dropping this)

Auxiliary Features
- Trends over time
- Filter by journal? 
- For average APC view, include average across all institutions for comparison

a report wouldn’t be a single super-flexible report, but a series of quite-flexible views of the data.

Mockups:
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275248
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275248_Institutions-01

https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275247
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275251
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275250
https://projects.invisionapp.com/share/WN7ABGOZF#/screens/158275249

We suggest that this report, upon opening for the first time, is populated with the user’s institution. If it is not known, suggest perhaps either the top 5 APC purchasers, or, a random 5 (is that a bad idea ??)

It seems reasonable that we’d introduce a limit on the amount of institutions to show on the chart.

Each report currently has a min/max/mean. Only the mean is really key, the other two can go

Some department/sub-department level reporting might also be useful here, though it's not clear yet how we do that

We will require a default period for the report: calendar/financial/academic year/month

Investigate possibilities for trends across time (see #14 )

**Comment by richard-jones** [comment]
This report is complete with the exception of the checkbox facet (see #21 ) and the "story"

@TomYeahOK - assigning to you for review, if you want to give me a list of changes.

**Comment by tdcodesthings** [comment]
Other than the CSS-y bits ([#27](https://github.com/JiscMonitor/monitor-uk/issues/27)), there is an issue with the scaling of the 'total expenditure' and 'average APC' views on the chart.

**Comment by tdcodesthings** [comment]
re. the scaling issue @richard-jones , I just noticed that resizing the browser forces the chart to reconsider the scaling and it gets it right -hope this is useful info!

**Comment by richard-jones** [comment]
Scaling issue fixed, and other issues with the report are captured elsewhere, so closing
