### ISSUE TITLE
Changes to search filter layout

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#50]
- [x] 1/ Some CSS to help get the title of it closer to the design in [this Gist](https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f).
- [x] 2/ Remove the 2px line under the word Filter
- [x] 3/ Facet headings to be in Stag Sans Light

**Comment by Steven-Eardley** [comment]
@richard-jones I don't think I can see that gist as intended.

**Comment by richard-jones** [comment]
Looks like all the gist links are broken, but they appear to work when you remove /edit.

Try: https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f
