### ISSUE TITLE
Changes to tabs on reports

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#51]
- [x] 1/ Don't use <strong>s on these as it adds a faux-bold
- [ ] 2/ Hover CSS - [see item 3 in this gist](https://gist.github.com/TomYeahOK/4a77219df34915aa83d6564ab996931f)
- [x] 3/ Add 'show:' label, per [mockup](https://invis.io/WN7ABGOZF#/158597190_Publisher_Report_-_Minimal_Filter-01_).

**Comment by richard-jones** [comment]
@Steven-Eardley - can you pick this one up too?

**Comment by Steven-Eardley** [comment]
Yup, having a look now.

**Comment by Steven-Eardley** [comment]
I couldn't really see what effect was desired for /2, (and nothing happened when I tried it) so i've left that.
