### ISSUE TITLE
Package for hand-over

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#52]
We need to do the following things to prep for hand-over:
- [x] create asset compilation scripts for each report for css and javascript
- [x] update public ui to use compiled assets, leaving demonstrators as to how to revert to the development assets
- [x] version the urls for assets, for cache busting purposes later
- [x] re-mount edges_build as edges, get rid of edges_build, and update all references
- [x] fork esprit at its current version to the JiscMonitor project space
- [x] fork magnificent-octopus at its current version to the JiscMonitor project space
- [x] fork edges at its current version to the JiscMonitor project space

**Comment by richard-jones** [comment]
When this is done, and tested on our staging environment, we'll need to ask for a redeploy

**Comment by richard-jones** [comment]
Oh, we should also merge to master and tag the release

**Comment by Steven-Eardley** [comment]
All done - 1.0.0 tagged, bagged, released.

**Comment by richard-jones** [comment]
Lovely, thank you!
