### ISSUE TITLE
Data load issue on Funder report

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#54]
Exact circumstances unknown, but some users have reported under:
- Google Chrome
- Windows 7

The following: 

![monitor uk funder data error](https://cloud.githubusercontent.com/assets/856138/18827172/54a2ae16-83c9-11e6-94f4-e6c39621013e.jpg)

We don't have any more information, and have so far been unable to reproduce.

It's particularly odd, as some of the data appears to have loaded.  My guess would be an error in the script, rather than a connection problem.

@Steven-Eardley - could you have a go at reproducing, perhaps with BrowserStack?

**Comment by ostephens** [comment]
I've tested on Win 7 Enterprise with Chrome 52.0.2743.116m but didn't see the issue
Also tried IE11 on same platform and again no issue
Also tested with no issues on my Mac with FF48.0.1 and 49.0.1, Chrome  53.0.2785.116 and Safari 10.0

**Comment by Steven-Eardley** [comment]
That's great, I reproduced the problem yesterday by using an old Chrome version - it was because I'd used `Set()` in the monitor report, not compatible with outdated browsers (chrome <38, ie <11).

So I did make a fix, and released it to monitoruk.cottagelabs.com yesterday evening.
