### ISSUE TITLE
Duplicate detection

### ISSUE THREAD

**Issue by richard-jones** [JiscMonitor/monitor-uk#9]
We need to be able to pull out duplicate payment/APCs from the dataset.  There are 3 different kinds of duplicates we might be interested in:
- Records where more than one APC has been paid at all
- Records where more than one organisation has paid an APC
- Records where more than one organisation has told us about an APC payment

Proposal is to place this as a search interface filter which allows constraint by those options

**Comment by richard-jones** [comment]
This has now been implemented on the test site, so is ready for review.  @TomYeahOK - I'll assign this to you once I've re-indexed the data on the test site, and you can actually play with the functionality.

**Comment by tdcodesthings** [comment]
This makes sense, and as was suggested (I think by you?), in the first instance the simplest way of clarifying the buttons that have been added would be to make them more descriptive, i.e. longer sentences, like the ones above.
